# Generated by Django 5.2.5 on 2025-08-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='hazard_score',
            field=models.FloatField(blank=True, help_text='Overall route hazard score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='hazard_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated alert counts and metrics'),
        ),
        migrations.AddField(
            model_name='route',
            name='risk_level',
            field=models.CharField(default='unknown', help_text='Overall risk level label', max_length=20),
        ),
        migrations.AddField(
            model_name='routeweatherpoint',
            name='hazard_score',
            field=models.FloatField(blank=True, help_text='Point hazard score (0-100)', null=True),
        ),
    ]
